title: Mori Mountain
description: Hokkaido Touch. Montana Grown. Glacier Tough.

url: https://morimountain406.github.io

remote_theme: just-the-docs/just-the-docs

color_scheme: light

search_enabled: true

nav_sort: case_insensitive

heading_anchors: true

aux_links:
  GitHub Repository: https://github.com/MoriMountain406/MoriMountain406.github.io

footer_content: "© Mori Mountain • Open regenerative systems research"

plugins:
  - jekyll-remote-theme
